# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de84fddedee969bff5b1a083d7038e3ebba66f2d340257e814d5bc7b1b8b3946a61f70fbbacbfb576586f3eed20776ed0df48b579043d0d8ce43fb8d176ac2b

test:
  secret_key_base: 8f4f607a82b75600650c5f55bbb65b578edad8983f1d142830fe2e451d80aa0666d2ff1b09c842ba0cb58d260a04da8559f61f7d88090d36c76617da69b24258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
